### ISSUE TITLE
I am getting Traceback error and No such file and Directory

### ISSUE THREAD

**Issue by WinXprt** [lukebaggett/google_socks#2]
![capture](https://user-images.githubusercontent.com/32786723/35739453-a91e5698-0857-11e8-9fb0-f210eed531b0.PNG)

**Comment by lukebaggett** [comment]
You’ll need to get a client_secrets.json file from the Google API Console and place it in the current directory. Running the script with “--setup” will give some instructions on how to do this. Let me know if you run into any issues.

**Comment by WinXprt** [comment]
Can you improve the Readme.md file with all possible steps(End-to-End)?  
So that it will easy for the users who is using this google socks.

**Comment by WinXprt** [comment]
Can you improve the Readme.md file with all possible steps?  
So that it will easy for the users who is using this google socks.

**Comment by WinXprt** [comment]
Thank You @lukebaggett for improving the Readme.md file.
